# Problem 1
To calculate the multiplication of two given matrices, the process is to multiply each row in matrix A with each column in matrix B. The resulting matrix is a 3x3 matrix whose entries can be calculated with the following formula:
$$
 C[i][j] = \sum_{k=0}^{2} A[i][k] * B[k][j]
$$
With that formula, we have:
$ C[0][0] = -1*0 + 2*0 + 3*2 = 6 \
 C[0][1] = -1*2 + 2*2 + 3*9 = 29 \
 C[0][2] = -1*1 + 2*(-8) + 3*(-1) = -20 \
 C[1][0] =  4*0 + -5*0 + 6*2 = 12 \
 C[1][1] =  4*2 + -5*2 + 6*9 = 52 \
 C[1][2] =  4*1 + -5*(-8) + 6*(-1) = 38 \
 C[2][0] =  7*0 + 8*0 + -9*2 = -18 \
 C[2][1] =  7*2 + 8*2 + -9*9 = -51 \
 C[2][2] =  7*1 + 8*(-8) + -9*(-1) = -48 $

# Problem 2
I use np.matmul() for calculation

In [13]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
multiplication_matrix = np.matmul(a_ndarray,b_ndarray)
print(multiplication_matrix)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# Problem 3

In [18]:
result_array = np.zeros((3,3))
for i in range(3):
    result_array[0][0] += a_ndarray[0][i] * b_ndarray[i][0]
print(result_array[0][0])

6.0


# Problem 4

In [19]:
def matrix_multiplication(matA, matB):
    result_array = np.zeros((len(matA),len(matB[0])))
    for i in range(len(matA)):
        for j in range(len(matB[0])):
            for k in range(len(matB)):
                   result_array[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
    return result_array
print(matrix_multiplication(a_ndarray,b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# Problem 5

In [25]:
def matrix_multiplication(matA, matB):
    if len(matA[0]) != len(matB):
        print("Invalid input, number of column of first matrix should be the same as number of row of second matrix")
        return -1
    result_array = np.zeros((len(matA),len(matB[0])))
    for i in range(len(matA)):
        for j in range(len(matB[0])):
            for k in range(len(matB)):
                   result_array[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
    return result_array
two_x_two = np.zeros((2,2))
three_x_three = np.zeros((3,3))
matrix_multiplication(two_x_two,three_x_three)

Invalid input, number of column of first matrix should be the same as number of row of second matrix


-1

# Problem 6
I use np.transpose() for solving this problem

In [26]:
a_trans = np.transpose(a_ndarray)
b_trans = np.transpose(b_ndarray)
print(matrix_multiplication(a_trans,b_trans))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
